version: 2.1

executors:
  default:
    working_directory: ~/my-tinycards
    docker:
      - image: tuanhnt1712/ruby2.5.1
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_PATH: vendor/bundle
          BUNDLE_RETRY: 3
          BUNDLER_VERSION: 2.0.1
          RAILS_ENV: test
          DB_HOST: 127.0.0.1
          DB_USERNAME: root
          DB_PASSWORD: ''
      - image: circleci/mysql:8.0.4
        command: [--default-authentication-plugin=mysql_native_password]
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
          MYSQL_ROOT_HOST: '%'
          MYSQL_DATABASE: app_test
          MYSQL_USER: root
      - cap_add: SYS_NICE
commands:
  configure_bundler:
    description: Configure bundler
    steps:
      - run:
          name: Configure bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler
jobs:
  build:
    executor: default
    steps:
      - checkout
      - run:
          name: "tesst"
          command: apt-get -y install tzdata
      - run:
          name: haha
          command: apt-get install -y libmysqlclient-dev
      - run:
          name: Install bundle
          command: bundle install
      - run:
          name: Setup DB
          command: bundle exec rails db:drop db:create db:migrate db:seed
      - run:
          name: RSpec
          command: bundle exec rspec spec
      - store_artifacts:
          path: coverage
      - run:
          name: Rubocop
          command: bundle exec rubocop app/ lib/ db/migrate/ config/
      - run:
          name: Brakeman
          command: bundle exec brakeman

workflows:
  version: 2
  integration:
    jobs:
      - build